name = "social-sync-worker"
main = "./src/worker.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat_v2"]
account_id = "bd4571b6716cd1df1a53823b80f0fb0c"
workers_dev = true

# KV Namespace for storing sync state
kv_namespaces = [
  { binding = "SYNC_STORE", id = "027acd77c1b346b19e6e159fe57397cd" }
]

[triggers]
crons = ["*/5 * * * *"]  # Run every 5 minutes (default)

[vars]
DEBUG = "false"
POSTS_TO_SYNC = "10"
IGNORE_REPOSTS = "true"
DRY_RUN = "true"  # Set to "true" to simulate sync without posting
MASTODON_URL = "https://hachyderm.io"  # Change this to your instance
MASTODON_USERNAME = "jerdog"  # Your Mastodon username
BLUESKY_USERNAME = "jerdog.dev"   # Your Bluesky handle

# Secrets that should be set using `wrangler secret put`:
# - MASTODON_ACCESS_TOKEN
# - BLUESKY_PASSWORD

# Node.js build settings
[build]
command = "npm install"

# Enable observability
[observability]
enabled = true
